//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace kursachMain
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class kursachDb : DbContext
    {
        public kursachDb()
            : base("name=kursachDb")
        {
            RecrutmentPlan = Set<ПланНабора>();
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Виды_практики> PractTupe { get; set; }
        public virtual DbSet<Группы> Grups { get; set; }
        public virtual DbSet<Договоры> Pacts { get; set; }
        public virtual DbSet<ПланНабора> RecrutmentPlan { get; set; }
        public virtual DbSet<Предприятия> Enterprices { get; set; }
        public virtual DbSet<Преподаватели> Techer { get; set; }
        public virtual DbSet<ПроведениеПрактики> ConductingPractice { get; set; }
        public virtual DbSet<Специальности> Spceialtes { get; set; }
        public virtual DbSet<Студенты> Students { get; set; }
        public virtual DbSet<Текущая_практика> Current { get; set; }
    }
}
