//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace kursachMain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Предприятия
    {
        public int ID_предприятия { get; set; }
        public string Название { get; set; }
        public string УНП { get; set; }
        public string Адрес { get; set; }
        public string Телефон { get; set; }
        public string Эл__почта { get; set; }
        public string Контактное_лицо { get; set; }
        public int IDЗаключенныхДоговоров { get; set; }
        public int IDНабораНаГод { get; set; }
    
        public virtual Договоры Договоры { get; set; }
        public virtual ПланНабора ПланНабора { get; set; }
    }
}
